spring:
  application:
    name: assignment
  datasource:
    url: jdbc:h2:mem:customerdb
    driver-class-name: org.h2.Driver
    username: primary
    #this could be encrypted using jasypt and used in teh application code.
    password: testingDB
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

logging:
  level:
    root: INFO
    com.anoop.assignment.web: DEBUG
    com.anoop.assignment.service: DEBUG
  file:
    name: logs/application.log